scheming_version: 2
dataset_type: service

dataset_fields:

- field_name: title
  label:
    en: Title
  preset: title
  form_placeholder: e.g. MyDataset, MyService, MyApp
  display_property: dc:title

- field_name: base_URL
  label:
    en: Base URL
  preset: title
  form_placeholder: as visible from your DSC
  display_property: dc:accessURL
  help_text: Should be something like http://containername:port/path/to/api

- field_name: name
  label: URL
  preset: package_slug
  form_placeholder: eg. camel-no-5
  display_property: dc:identifier

- field_name: owner_org
  label:
    en: Rights Holder
  preset: dataset_organization
  display_property : dct:rightsHolder

- field_name: license_id
  label: License
  form_snippet: license.html
  help_text: License definitions and additional information can be found at http://opendefinition.org/

- field_name: theme
  label:
    en: Theme
  help_text: Theme
  help_inline: true
  preset: select
  choices:
  - value: https://trusts.org/vacabulary/themes/Industry
    label: Industry
  - value: https://trusts.org/vacabulary/themes/Health
    label: Health
  - value: https://trusts.org/vacabulary/themes/Agriculture
    label: Agriculture
  - value: https://trusts.org/vacabulary/themes/Oil
    label: Oil
  - value: https://trusts.org/vacabulary/themes/Enterprises
    label: Enterprises

resource_fields:

- field_name: url
  label: Resource
  preset: resource_url_upload
  form_placeholder: http://example.com/example.json
  upload_label: ""